(function() {
	'use strict';

	const TRAIN_DATA = {
		"NJT LRV-3": {
			"id": "NJT LRV-3",
			"name": "NJT LRV-3",
			"description": "This is an unnamed articulated low-floor light-rail vehicle built by Kinki-Sharyo for New Jersey Transit, specifically Hudson-Bergen Light Rail and Newark Light Rail. It has been in service since 2000. This is the original, 3 section version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 24.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 67,
				"carLength": 9.14,
				"minCars": 3,
				"maxCars": 6,
				"carsPerCarSet": 3,
				"carCost": 1166667,
				"trainWidth": 2.68,
				"minStationLength": 54.84,
				"maxStationLength": 60,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["NJT LRV-3", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#E06C9E"},
			"isFixed": false,
			"location": {
				"city": ["NYC"],
				"country": ["US"],
				"continent": ["North America"],
			},
			"manufacturer": ["Kinki Sharyo"],
			"tag": ["Standard LRT"],
		},
		"NJT LRV-5": {
			"id": "NJT LRV-5",
			"name": "NJT LRV-5",
			"description": "This is an unnamed articulated low-floor light-rail vehicle built by Kinki-Sharyo for New Jersey Transit, specifically Hudson-Bergen Light Rail and Newark Light Rail. It has been in service since 2000. This is the 5 section version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 24.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 60,
				"carLength": 7.74,
				"minCars": 5,
				"maxCars": 5,
				"carsPerCarSet": 5,
				"carCost": 920000,
				"trainWidth": 2.68,
				"minStationLength": 38.7,
				"maxStationLength": 60,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["NJT LRV-5", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#FF7CB5"},
			"isFixed": false,
			"location": {
				"city": ["NYC"],
				"country": ["US"],
				"continent": ["North America"],
			},
			"manufacturer": ["Kinki Sharyo"],
			"tag": ["Standard LRT"],
		},
		"FE-10 (MXC)": {
			"id": "FE-10 (MXC)",
			"name": "FE-10 (MXC)",
			"description": "The FE-10 is a steel-wheeled model of EMU built by CAF used on the Mexico City Metro, first used in 2012.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.2,
				"maxDeceleration": 1.2,
				"maxSpeed": 25.0,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 210,
				"carLength": 20.14,
				"minCars": 7,
				"maxCars": 7,
				"carsPerCarSet": 7,
				"carCost": 5659704,
				"trainWidth": 2.8,
				"minStationLength": 140.98000000000002,
				"maxStationLength": 150,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["FE-10 (MXC)", "750V Metro (CAT|MW)"],
			"appearance": { "color": "#B0A32A"},
			"isFixed": false,
			"location": {
				"city": ["MXC"],
				"country": ["MX"],
				"continent": ["Central America"],
			},
			"manufacturer": ["CAF"],
			"tag": ["Standard Metro"],
		},
		"NM-16 (MXC)": {
			"id": "NM-16 (MXC)",
			"name": "NM-16 (MXC)",
			"description": "The NM-16 is a rubber-tyred model of EMU built by CAF used on the Mexico City Metro",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.43,
				"maxDeceleration": 1.43,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 249,
				"carLength": 16.77,
				"minCars": 9,
				"maxCars": 9,
				"carsPerCarSet": 9,
				"carCost": 2165780,
				"trainWidth": 2.5,
				"minStationLength": 150.93,
				"maxStationLength": 175,
				"baseTrackCost": 75000,
				"baseStationCost": 112500000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 20250000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 4.50,
				"STANDARD_TUNNEL": 2.00,
				"CUT_AND_COVER": 1.00,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["NM-16 (MXC)", "MXC Rubber Metro"],
			"appearance": { "color": "#F04E98"},
			"isFixed": false,
			"location": {
				"city": ["MXC"],
				"country": ["MX"],
				"continent": ["Central America"],
			},
			"manufacturer": ["CAF"],
			"tag": ["Rubber Metro"],
		},
		"Cuautitlán-Buenavista": {
			"id": "Cuautitlán-Buenavista",
			"name": "Cuautitlán-Buenavista",
			"description": "The Cuautitlán-Buenavista is a commuter rail EMU built by CAF used on Mexico City's Tren Suburbano that entered service in 2008. ",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.0,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 284,
				"carLength": 25.5,
				"minCars": 3,
				"maxCars": 8,
				"carsPerCarSet": 1,
				"carCost": 3300000,
				"trainWidth": 3.01,
				"minStationLength": 204.0,
				"maxStationLength": 220,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["Cuautitlán-Buenavista", "25-GF Main Line (CAT|AAR)"],
			"appearance": { "color": "#BE1C00"},
			"isFixed": false,
			"location": {
				"city": ["MXC"],
				"country": ["MX"],
				"continent": ["Central America"],
			},
			"manufacturer": ["CAF"],
			"tag": ["Standard Commuter"],
		},
		"TE-90": {
			"id": "TE-90",
			"name": "TE-90",
			"description": "The TE-90 is an articulated high-floor light-rail vehicle built by Bombardier that has been in service in Mexico City since 1990. It is also knwon as the TE-96, 08, and 12",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.0,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 150,
				"carLength": 14.78,
				"minCars": 2,
				"maxCars": 2,
				"carsPerCarSet": 2,
				"carCost": 4500000,
				"trainWidth": 2.65,
				"minStationLength": 29.56,
				"maxStationLength": 35,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["TE-90", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#0055B8"},
			"isFixed": false,
			"location": {
				"city": ["MXC"],
				"country": ["MX"],
				"continent": ["Central America"],
			},
			"manufacturer": ["Bombardier"],
			"tag": ["Standard LRT"],
		},
		"MultiLevel Coach III EMU": {
			"id": "MultiLevel Coach III EMU",
			"name": "MultiLevel Coach III EMU",
			"description": "The MultiLevel Coach III is a commuter rail EMU built by Bombardier/Alstom that entered service in 2006. They are used on multiple networks across Eastern North America.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 0.8,
				"maxDeceleration": 1.05,
				"maxSpeed": 44.7,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 135,
				"carLength": 25.91,
				"minCars": 3,
				"maxCars": 12,
				"carsPerCarSet": 1,
				"carCost": 4800000,
				"trainWidth": 3.05,
				"minStationLength": 310.92,
				"maxStationLength": 320,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["MultiLevel Coach III EMU", "NEC 12-25"," NEC 12.5-60"," 25-GF Main Line (CAT|AAR)"],
			"appearance": { "color": "#00A3E3"},
			"isFixed": false,
			"location": {
				"city": ["NYC"],
				"country": ["US"],
				"continent": ["North America"],
			},
			"manufacturer": ["Bombardier"],
			"tag": ["Standard Commuter"],
		},
		"ALP45-BMLC": {
			"id": "ALP45-BMLC",
			"name": "ALP45-BMLC",
			"description": "The Bombardier ALP-45 is a dual-mode locomotive that first entered service in 2010. This specific trainset carries passengers with Bombardier MultiLevel Coaches in their trailer configuration.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 0.72,
				"maxDeceleration": 1.05,
				"maxSpeed": 44.7,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 150,
				"carLength": 25.91,
				"minCars": 4,
				"maxCars": 10,
				"carsPerCarSet": 1,
				"carCost": 5703289,
				"trainWidth": 3.05,
				"minStationLength": 259.1,
				"maxStationLength": 320,
				"baseTrackCost": 37500,
				"baseStationCost": 56250000,
				"trainOperationalCostPerHour": 800,
				"carOperationalCostPerHour": 80,
				"scissorsCrossoverCost": 11250000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["ALP45-BMLC", "U.S. Commuter Diesel"," NEC 12-25"," NEC 12.5-60"," 25-GF Main Line (CAT|AAR)"," 1.5kV Metro (CAT|AAR)"],
			"appearance": { "color": "#F9A533"},
			"isFixed": false,
			"location": {
				"city": ["NYC","MTL"],
				"country": ["US","CA"],
				"continent": ["North America","North America"],
			},
			"manufacturer": ["Bombardier"],
			"tag": ["Diesel Commuter"],
		},
		"ALP46-BMLC": {
			"id": "ALP46-BMLC",
			"name": "ALP46-BMLC",
			"description": "The Bombardier ALP-45 is an electric locomotive that first entered service in 2001. This specific trainset carries passengers with Bombardier MultiLevel Coaches in their trailer configuration.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 0.72,
				"maxDeceleration": 1.05,
				"maxSpeed": 44.7,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 150,
				"carLength": 25.91,
				"minCars": 4,
				"maxCars": 10,
				"carsPerCarSet": 1,
				"carCost": 5703289,
				"trainWidth": 3.05,
				"minStationLength": 259.1,
				"maxStationLength": 320,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["ALP46-BMLC", "NEC 12-25"," NEC 12.5-60"," 25-GF Main Line (CAT|AAR)"],
			"appearance": { "color": "#EE3E42"},
			"isFixed": false,
			"location": {
				"city": ["NYC"],
				"country": ["US"],
				"continent": ["North America"],
			},
			"manufacturer": ["Bombardier"],
			"tag": ["Standard Commuter"],
		},
		"Flexity Swift LF": {
			"id": "Flexity Swift LF",
			"name": "Flexity Swift LF",
			"description": "The Flexity Swift is a series of articulated tram/LRT/light metro vehicles produced by Bombardier/Alstom that have been in service for decades around the world. This is a genericized version of the low-floor models.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.2,
				"maxDeceleration": 1.3,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 69,
				"carLength": 9.67,
				"minCars": 3,
				"maxCars": 12,
				"carsPerCarSet": 3,
				"carCost": 1723380,
				"trainWidth": 2.65,
				"minStationLength": 116.03999999999999,
				"maxStationLength": 120,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Flexity Swift LF", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#76BC21"},
			"isFixed": false,
			"location": {
				"city": ["LDN","IST"],
				"country": ["UK","TR"],
				"continent": ["Europe","West Asia"],
			},
			"manufacturer": ["Bombardier"],
			"tag": ["Standard LRT"],
		},
		"AnsaldoBreda DM-7": {
			"id": "AnsaldoBreda DM-7",
			"name": "AnsaldoBreda DM-7",
			"description": "The Hitachi Rail Italy Driverless Metro (formerly AnsaldoBreda) is a fully autonomous EMU family used across the globe. This specific model is based on those used by Lima's Metro since 2017.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.3,
				"maxSpeed": 25.0,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 184,
				"carLength": 17.82,
				"minCars": 6,
				"maxCars": 7,
				"carsPerCarSet": 1,
				"carCost": 1984127,
				"trainWidth": 2.71,
				"minStationLength": 124.74000000000001,
				"maxStationLength": 130,
				"baseTrackCost": 50000,
				"baseStationCost": 78750000,
				"trainOperationalCostPerHour": 400,
				"carOperationalCostPerHour": 40,
				"scissorsCrossoverCost": 15750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["AnsaldoBreda DM-7", "1.5kV Auto Metro (CAT|MW)"," 750V Metro (TRU|MS)"," 750V Auto Metro (TRA|AAR)"," 1.5kV Auto Metro (TRU|AAR)"],
			"appearance": { "color": "#FFB81C"},
			"isFixed": false,
			"location": {
				"city": ["LIM"],
				"country": ["PE"],
				"continent": ["South America"],
			},
			"manufacturer": ["AnsaldoBreda","Hitachi"],
			"tag": ["Automated Metro"],
		},
		"Citadis 305 N": {
			"id": "Citadis 305 N",
			"name": "Citadis 305 N",
			"description": "The Citadis is a family of articulated low-floor LRVs built by Alstom that have been in service since 2000. This is the 5th generation, narrow, five section version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 60,
				"carLength": 8.68,
				"minCars": 5,
				"maxCars": 5,
				"carsPerCarSet": 5,
				"carCost": 1000000,
				"trainWidth": 2.4,
				"minStationLength": 43.4,
				"maxStationLength": 70,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.06,
				"STANDARD_TUNNEL": 2.25,
				"CUT_AND_COVER": 1.13,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.70
			},
			"compatibleTrackTypes": ["Citadis 305 N", "750V LRV (CAT|UN)"],
			"appearance": { "color": "#0094FF"},
			"isFixed": false,
			"location": {
				"city": ["PAR","ATH"],
				"country": ["FR","GR"],
				"continent": ["Western Europe","Southern Europe"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard LRT"],
		},
		"Citadis 305": {
			"id": "Citadis 305",
			"name": "Citadis 305",
			"description": "The Citadis is a family of articulated low-floor LRVs built by Alstom that have been in service since 2000. This is the 5th generation, five section version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 44,
				"carLength": 6.44,
				"minCars": 5,
				"maxCars": 5,
				"carsPerCarSet": 5,
				"carCost": 1000000,
				"trainWidth": 2.65,
				"minStationLength": 32.2,
				"maxStationLength": 70,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Citadis 305", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#0094FF"},
			"isFixed": false,
			"location": {
				"city": ["BCN","T-A"],
				"country": ["ES","IL"],
				"continent": ["Southern Europe","West Asia"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard LRT"],
		},
		"81-717/81-714": {
			"id": "81-717/81-714",
			"name": "81-717/81-714",
			"description": "The Metrovagonmash 81-717/81-714 is a Soviet era heavy metro EMU that entered service in 1977. It remains in use across the former USSR.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.2,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 260,
				"carLength": 19.21,
				"minCars": 1,
				"maxCars": 8,
				"carsPerCarSet": 1,
				"carCost": 1000000,
				"trainWidth": 2.67,
				"minStationLength": 153.68,
				"maxStationLength": 160,
				"baseTrackCost": 68200,
				"baseStationCost": 102300000,
				"trainOperationalCostPerHour": 700,
				"carOperationalCostPerHour": 70,
				"scissorsCrossoverCost": 20625000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 4.50,
				"STANDARD_TUNNEL": 2.00,
				"CUT_AND_COVER": 1.00,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["81-717/81-714", "825V USSR Metro (TRU|MS)"," 825V Metro (TRA|MW)"],
			"appearance": { "color": "#32AB53"},
			"isFixed": false,
			"location": {
				"city": ["USSR","IEV","BUD"],
				"country": ["USSR","UA","HU"],
				"continent": ["USSR","Eastern Europe","Eastern Europe"],
			},
			"manufacturer": ["Metrovagonmash "],
			"tag": ["Standard Metro"],
		},
		"Twist Foxtrot": {
			"id": "Twist Foxtrot",
			"name": "Twist Foxtrot",
			"description": "The Twist is a low-floor articulated LRV built by a Polish company named PESA that entered service in 2012. The 71-414 Foxtrot is a variant made for Kyiv and Moscow. Acceleration is a guesstimate. Capacity is increased artificially due to game processing requirements. Cost is an estimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.3,
				"maxSpeed": 20.8,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 67,
				"carLength": 8.75,
				"minCars": 3,
				"maxCars": 3,
				"carsPerCarSet": 3,
				"carCost": 750000,
				"trainWidth": 2.5,
				"minStationLength": 26.25,
				"maxStationLength": 30,
				"baseTrackCost": 55000,
				"baseStationCost": 82500000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 16500000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Twist Foxtrot", "600V USSR LRV (CAT|NAR)"],
			"appearance": { "color": "#001C4A"},
			"isFixed": false,
			"location": {
				"city": ["IEV"],
				"country": ["UA"],
				"continent": ["Eastern Europe"],
			},
			"manufacturer": ["PESA"],
			"tag": ["Standard LRT"],
		},
		"K-1T": {
			"id": "K-1T",
			"name": "K-1T",
			"description": "The K-1T is a low-floor articulated LRV built by Tatra-Yug that entered service in 2020. Acceleration is a guesstimate. Capacity is increased artificially due to game processing requirements. Cost is an estimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.3,
				"maxSpeed": 20.8,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 67,
				"carLength": 8.67,
				"minCars": 3,
				"maxCars": 3,
				"carsPerCarSet": 3,
				"carCost": 750000,
				"trainWidth": 2.5,
				"minStationLength": 26.009999999999998,
				"maxStationLength": 30,
				"baseTrackCost": 55000,
				"baseStationCost": 82500000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 16500000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["K-1T", "600V USSR LRV (CAT|NAR)"],
			"appearance": { "color": "#35BCED"},
			"isFixed": false,
			"location": {
				"city": ["IEV"],
				"country": ["UA"],
				"continent": ["Eastern Europe"],
			},
			"manufacturer": ["Tatra-Yug"],
			"tag": ["Standard LRT"],
		},
		"Generation 3 (ATH)": {
			"id": "Generation 3 (ATH)",
			"name": "Generation 3 (ATH)",
			"description": "The 3rd Generation of Athens lines 2 and 3 rolling stock is a heavy metro EMU built by Siemens and Hyundai that entered service in 2014.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.1,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 172,
				"carLength": 17.67,
				"minCars": 3,
				"maxCars": 6,
				"carsPerCarSet": 3,
				"carCost": 1806111,
				"trainWidth": 2.8,
				"minStationLength": 106.02000000000001,
				"maxStationLength": 110,
				"baseTrackCost": 62500,
				"baseStationCost": 93750000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 18750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 4.50,
				"STANDARD_TUNNEL": 2.00,
				"CUT_AND_COVER": 1.00,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Generation 3 (ATH)", "750V Metro (TRA|MW)"],
			"appearance": { "color": "#10069F"},
			"isFixed": false,
			"location": {
				"city": ["ATH"],
				"country": ["GR"],
				"continent": ["Southern Europe"],
			},
			"manufacturer": ["Hyundai","Siemens"],
			"tag": ["Standard Metro"],
		},
		"Desiro Classic (ATH)": {
			"id": "Desiro Classic (ATH)",
			"name": "Desiro Classic (ATH)",
			"description": "The Siemens Desiro Classic is a family of metro DMUs and EMUs in service across the world since 1999. This model is the EMU used by Athens commuter rail. Cost is an estimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.1,
				"maxDeceleration": 1.1,
				"maxSpeed": 44.4,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 63,
				"carLength": 17.87,
				"minCars": 5,
				"maxCars": 10,
				"carsPerCarSet": 5,
				"carCost": 4300000,
				"trainWidth": 2.8,
				"minStationLength": 178.70000000000002,
				"maxStationLength": 200,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Desiro Classic (ATH)", "25-GF Main Line (CAT|MW)"],
			"appearance": { "color": "#004587"},
			"isFixed": false,
			"location": {
				"city": ["ATH"],
				"country": ["GR"],
				"continent": ["Southern Europe"],
			},
			"manufacturer": ["Siemens"],
			"tag": ["Standard Commuter"],
		},
		"Sirio (ATH)": {
			"id": "Sirio (ATH)",
			"name": "Sirio (ATH)",
			"description": "The Sirio is a artiuculated low-floor LRV family built by AnsaldoBreda/Hitachi that has been in service since 2002. This is the variant used by the Athens tram network. Acceleration is guesstimated.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 54,
				"carLength": 6.46,
				"minCars": 5,
				"maxCars": 5,
				"carsPerCarSet": 5,
				"carCost": 580006,
				"trainWidth": 2.4,
				"minStationLength": 32.3,
				"maxStationLength": 40,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.06,
				"STANDARD_TUNNEL": 2.25,
				"CUT_AND_COVER": 1.13,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.70
			},
			"compatibleTrackTypes": ["Sirio (ATH)", "750V LRV (CAT|UN)"],
			"appearance": { "color": "#83B81A"},
			"isFixed": false,
			"location": {
				"city": ["ATH"],
				"country": ["GR"],
				"continent": ["Southern Europe"],
			},
			"manufacturer": ["AnsaldoBreda"],
			"tag": ["Standard LRT"],
		},
		"IÉ 22000": {
			"id": "IÉ 22000",
			"name": "IÉ 22000",
			"description": "The IÉ Class 22000 is an Irish DMU used for both commuter rail and intercity services. It was built by Hyundai Rotem and entered service in 2007. Acceleration is guesstimated. Cost is an estimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 0.7,
				"maxDeceleration": 0.7,
				"maxSpeed": 44.4,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 100,
				"carLength": 23.4,
				"minCars": 3,
				"maxCars": 10,
				"carsPerCarSet": 1,
				"carCost": 3000000,
				"trainWidth": 2.85,
				"minStationLength": 234.0,
				"maxStationLength": 250,
				"baseTrackCost": 41250,
				"baseStationCost": 61875000,
				"trainOperationalCostPerHour": 800,
				"carOperationalCostPerHour": 80,
				"scissorsCrossoverCost": 12375000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IÉ 22000", "Irish Diesel Main Line"],
			"appearance": { "color": "#169B62"},
			"isFixed": false,
			"location": {
				"city": ["DUB"],
				"country": ["IE"],
				"continent": ["Western Europe"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Diesel Commuter"],
		},
		"IÉ 29000": {
			"id": "IÉ 29000",
			"name": "IÉ 29000",
			"description": "The IÉ Class 29000 is an Irish commuter rail DMU built by CAF that entered service in 2003. Acceleration is guesstimated. Cost is an estimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 0.9,
				"maxDeceleration": 0.9,
				"maxSpeed": 33.3,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 205,
				"carLength": 20.37,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 3000000,
				"trainWidth": 2.9,
				"minStationLength": 162.96,
				"maxStationLength": 250,
				"baseTrackCost": 41250,
				"baseStationCost": 61875000,
				"trainOperationalCostPerHour": 800,
				"carOperationalCostPerHour": 80,
				"scissorsCrossoverCost": 12375000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IÉ 29000", "Irish Diesel Main Line"],
			"appearance": { "color": "#FF883E"},
			"isFixed": false,
			"location": {
				"city": ["DUB"],
				"country": ["IE"],
				"continent": ["Western Europe"],
			},
			"manufacturer": ["CAF"],
			"tag": ["Diesel Commuter"],
		},
		"Citadis 401": {
			"id": "Citadis 401",
			"name": "Citadis 401",
			"description": "The Citadis is a family of articulated low-floor LRVs built by Alstom that have been in service since 2000. This is the 1st generation, seven section version. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 38,
				"carLength": 5.83,
				"minCars": 7,
				"maxCars": 7,
				"carsPerCarSet": 7,
				"carCost": 1000000,
				"trainWidth": 2.4,
				"minStationLength": 40.81,
				"maxStationLength": 60,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.06,
				"STANDARD_TUNNEL": 2.25,
				"CUT_AND_COVER": 1.13,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.70
			},
			"compatibleTrackTypes": ["Citadis 401", "750V LRV (CAT|UN)"],
			"appearance": { "color": "#4F3189"},
			"isFixed": false,
			"location": {
				"city": ["DUB"],
				"country": ["IE"],
				"continent": ["Western Europe"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard LRT"],
		},
		"Citadis 502": {
			"id": "Citadis 502",
			"name": "Citadis 502",
			"description": "The Citadis is a family of articulated low-floor LRVs built by Alstom that have been in service since 2000. This is the 2nd generation, nine section version. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 45,
				"carLength": 6.08,
				"minCars": 9,
				"maxCars": 9,
				"carsPerCarSet": 9,
				"carCost": 1000000,
				"trainWidth": 2.4,
				"minStationLength": 54.72,
				"maxStationLength": 60,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.06,
				"STANDARD_TUNNEL": 2.25,
				"CUT_AND_COVER": 1.13,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.70
			},
			"compatibleTrackTypes": ["Citadis 502", "750V LRV (CAT|UN)"],
			"appearance": { "color": "#764ACE"},
			"isFixed": false,
			"location": {
				"city": ["DUB"],
				"country": ["IE"],
				"continent": ["Western Europe"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard LRT"],
		},
		"IST M1": {
			"id": "IST M1",
			"name": "IST M1",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the light metro stock that entered service in 1988 on the M1, as made by ABB. Acceleration is a guesstimate. Cost is an estimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.0,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 257,
				"carLength": 23.2,
				"minCars": 4,
				"maxCars": 4,
				"carsPerCarSet": 4,
				"carCost": 1000000,
				"trainWidth": 2.65,
				"minStationLength": 92.8,
				"maxStationLength": 100,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 700,
				"carOperationalCostPerHour": 70,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IST M1", "750V Metro (CAT|MS)"],
			"appearance": { "color": "#E22014"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["ABB"],
			"tag": ["Standard Metro"],
		},
		"IST M2 2008": {
			"id": "IST M2 2008",
			"name": "IST M2 2008",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the heavy metro stock that entered service in 2008 on the M2, as made by Hyundai. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.1,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 238,
				"carLength": 21.55,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 2139368,
				"trainWidth": 3.05,
				"minStationLength": 172.4,
				"maxStationLength": 190,
				"baseTrackCost": 62000,
				"baseStationCost": 93000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 18750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.63,
				"STANDARD_TUNNEL": 2.50,
				"CUT_AND_COVER": 1.25,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M2 2008", "750V Metro (TRU|AAR)"],
			"appearance": { "color": "#009943"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard Metro"],
		},
		"IST M2 2017": {
			"id": "IST M2 2017",
			"name": "IST M2 2017",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the heavy metro stock that entered service in 2017 on the M2, as made by Hyundai. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.1,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 238,
				"carLength": 21.57,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 1354583,
				"trainWidth": 3.05,
				"minStationLength": 172.56,
				"maxStationLength": 190,
				"baseTrackCost": 62000,
				"baseStationCost": 93000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 18750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.63,
				"STANDARD_TUNNEL": 2.50,
				"CUT_AND_COVER": 1.25,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M2 2017", "750V Metro (TRU|AAR)"],
			"appearance": { "color": "#00B54E"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Standard Metro"],
		},
		"IST M3": {
			"id": "IST M3",
			"name": "IST M3",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the heavy metro stock that entered service in 2009 on the M3 and M9, as made by Alstom. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 241,
				"carLength": 21.55,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 1365630,
				"trainWidth": 2.78,
				"minStationLength": 172.4,
				"maxStationLength": 190,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IST M3", "1.5kV Metro (CAT|MW)"," 1.5kV Metro (CAT|AAR)"],
			"appearance": { "color": "#00A8E2"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Standard Metro"],
		},
		"IST M4": {
			"id": "IST M4",
			"name": "IST M4",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the heavy metro stock that entered service in 2010 on the M4, as made by CAF. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 258,
				"carLength": 22.43,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 1374138,
				"trainWidth": 3.01,
				"minStationLength": 179.44,
				"maxStationLength": 190,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M4", "1.5kV Metro (CAT|AAR)"],
			"appearance": { "color": "#E91977"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard Metro"],
		},
		"IST M5": {
			"id": "IST M5",
			"name": "IST M5",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the Automated Metro stock that entered service in 2017 on the M5, as made by CAF and Mitsubishi. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 270,
				"carLength": 21.5,
				"minCars": 6,
				"maxCars": 6,
				"carsPerCarSet": 6,
				"carCost": 1122508,
				"trainWidth": 3.02,
				"minStationLength": 129.0,
				"maxStationLength": 140,
				"baseTrackCost": 50000,
				"baseStationCost": 78750000,
				"trainOperationalCostPerHour": 400,
				"carOperationalCostPerHour": 40,
				"scissorsCrossoverCost": 15750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M5", "750V Auto Metro (CAT|AAR)"],
			"appearance": { "color": "#672C65"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Mitsubishi","CAF"],
			"tag": ["Automated Metro"],
		},
		"IST M6": {
			"id": "IST M6",
			"name": "IST M6",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the heavy metro stock that entered service in 1999 on the M2 that now mainly serves the M6, as made by Alstom. Acceleration is a guesstimate. Cost is an estimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 234,
				"carLength": 21.55,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 1000000,
				"trainWidth": 3.05,
				"minStationLength": 172.4,
				"maxStationLength": 190,
				"baseTrackCost": 62000,
				"baseStationCost": 93000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 18750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.63,
				"STANDARD_TUNNEL": 2.50,
				"CUT_AND_COVER": 1.25,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M6", "750V Metro (TRU|AAR)"],
			"appearance": { "color": "#C9AA78"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard Metro"],
		},
		"IST M7/M8": {
			"id": "IST M7/M8",
			"name": "IST M7/M8",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the Automated Metro stock that entered service in 2020 on the M7 and M8, as made by Hyundai. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.1,
				"maxDeceleration": 1.1,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 301,
				"carLength": 22.5,
				"minCars": 4,
				"maxCars": 8,
				"carsPerCarSet": 4,
				"carCost": 1109302,
				"trainWidth": 3.1,
				"minStationLength": 180.0,
				"maxStationLength": 190,
				"baseTrackCost": 50000,
				"baseStationCost": 78750000,
				"trainOperationalCostPerHour": 400,
				"carOperationalCostPerHour": 40,
				"scissorsCrossoverCost": 15750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["IST M7/M8", "1.5kV Auto Metro (CAT|AAR)"],
			"appearance": { "color": "#F29FC0"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Automated Metro"],
		},
		"IST M11": {
			"id": "IST M11",
			"name": "IST M11",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the high speed heavy metro stock that entered service in 2023 on the M11, as made by CRRC. Acceleration and vehicle length are a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.23,
				"maxDeceleration": 1.34,
				"maxSpeed": 33.3,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 286,
				"carLength": 22.04,
				"minCars": 4,
				"maxCars": 4,
				"carsPerCarSet": 4,
				"carCost": 1260227,
				"trainWidth": 2.65,
				"minStationLength": 88.16,
				"maxStationLength": 100,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IST M11", "1.5kV Metro (CAT|MS)"],
			"appearance": { "color": "#AC5390"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["CRRC"],
			"tag": ["Standard Metro"],
		},
		"IST M12": {
			"id": "IST M12",
			"name": "IST M12",
			"description": "The Istanbul Metro has a variety of nameless rolling stock. This is the automated metro stock that will enter service on the M12, as made by Hyundai Rotem. Acceleration and vehicle length are a guesstimate.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.34,
				"maxDeceleration": 1.34,
				"maxSpeed": 22.2,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 270,
				"carLength": 21.5,
				"minCars": 4,
				"maxCars": 4,
				"carsPerCarSet": 4,
				"carCost": 1053333,
				"trainWidth": 2.9,
				"minStationLength": 86.0,
				"maxStationLength": 100,
				"baseTrackCost": 50000,
				"baseStationCost": 78750000,
				"trainOperationalCostPerHour": 400,
				"carOperationalCostPerHour": 40,
				"scissorsCrossoverCost": 15750000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["IST M12", "1.5kV Auto Metro (CAT|LSS)"],
			"appearance": { "color": "#C9D200"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Automated Metro"],
		},
		"TCDD E32000": {
			"id": "TCDD E32000",
			"name": "TCDD E32000",
			"description": "The TCDD E32000 is a commuter rail EMU built by Hyundai for Istanbul's Maramay commuter network that entered service in 2012. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.0,
				"maxSpeed": 25.0,
				"maxSpeedLocalStation": 15.0,
				"capacityPerCar": 300,
				"carLength": 22.5,
				"minCars": 5,
				"maxCars": 10,
				"carsPerCarSet": 5,
				"carCost": 1566709,
				"trainWidth": 3.1,
				"minStationLength": 225.0,
				"maxStationLength": 250,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 600,
				"carOperationalCostPerHour": 60,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 8.44,
				"STANDARD_TUNNEL": 3.75,
				"CUT_AND_COVER": 1.88,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.90
			},
			"compatibleTrackTypes": ["TCDD E32000", "25-GF Main Line (CAT|UIC)"],
			"appearance": { "color": "#392F85"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Hyundai"],
			"tag": ["Standard Commuter"],
		},
		"Urbos 100 (T-A)": {
			"id": "Urbos 100 (T-A)",
			"name": "Urbos 100 (T-A)",
			"description": "The Urbos family are articulated low-floor light-rail vehicles built by CAF that have been in service across the world since the 90s. This specific model is based on the Tel-Aviv Light Rail's version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.2,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 40,
				"carLength": 7.0,
				"minCars": 5,
				"maxCars": 10,
				"carsPerCarSet": 5,
				"carCost": 1000000,
				"trainWidth": 2.65,
				"minStationLength": 70.0,
				"maxStationLength": 75,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Urbos 100 (T-A)", "1.5kV LRV (CAT|MS)"],
			"appearance": { "color": "#BA34B1"},
			"isFixed": false,
			"location": {
				"city": ["T-A"],
				"country": ["IL"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["CAF"],
			"tag": ["Standard LRT"],
		},
		"Citadis 304": {
			"id": "Citadis 304",
			"name": "Citadis 304",
			"description": "The Citadis is a family of articulated low-floor LRVs built by Alstom that have been in service since 2000. This is the 4th generation, five section version.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.2,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 82,
				"carLength": 9.53,
				"minCars": 3,
				"maxCars": 6,
				"carsPerCarSet": 3,
				"carCost": 1000000,
				"trainWidth": 2.65,
				"minStationLength": 57.17999999999999,
				"maxStationLength": 70,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["Citadis 304", "750V LRV (CAT|MS)"],
			"appearance": { "color": "#004987"},
			"isFixed": false,
			"location": {
				"city": ["IST"],
				"country": ["TR"],
				"continent": ["West Asia"],
			},
			"manufacturer": ["Alstom"],
			"tag": ["Standard LRT"],
		},
		"9000 Series (Lima)": {
			"id": "9000 Series (Lima)",
			"name": "9000 Series (Lima)",
			"description": "The Alstom Metropolis is a series of metro EMUs in service across the world since 1993. The Series 9000 is a heavy metro variant built for the Lima Metro that entered service in 2016. Acceleration is guesstimated.",
			"allowAtGradeRoadCrossing": false,
			"stats": {
				"maxAcceleration": 1.3,
				"maxDeceleration": 1.3,
				"maxSpeed": 25.0,
				"maxSpeedLocalStation": 13.0,
				"capacityPerCar": 200,
				"carLength": 17.0,
				"minCars": 6,
				"maxCars": 6,
				"carsPerCarSet": 6,
				"carCost": 1980896,
				"trainWidth": 2.71,
				"minStationLength": 102.0,
				"maxStationLength": 110,
				"baseTrackCost": 50000,
				"baseStationCost": 75000000,
				"trainOperationalCostPerHour": 500,
				"carOperationalCostPerHour": 50,
				"scissorsCrossoverCost": 15000000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 6.75,
				"STANDARD_TUNNEL": 3.00,
				"CUT_AND_COVER": 1.50,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.80
			},
			"compatibleTrackTypes": ["9000 Series (Lima)", "1.5kV Metro (CAT|BCN)"],
			"appearance": { "color": "#47AA42"},
			"isFixed": false,
			"location": {
				"city": ["LIM"],
				"country": ["PE"],
				"continent": ["South America"],
			},
			"manufacturer": [""],
			"tag": ["Standard Metro"],
		},
		"TMK 2200": {
			"id": "TMK 2200",
			"name": "TMK 2200",
			"description": "The TMK 2300 is a low floor articulated LRV produced by Crotram for the Zagreb tram network. It entered service in 2005. Acceleration is a guesstimate.",
			"allowAtGradeRoadCrossing": true,
			"stats": {
				"maxAcceleration": 1.0,
				"maxDeceleration": 1.0,
				"maxSpeed": 19.4,
				"maxSpeedLocalStation": 6.7,
				"capacityPerCar": 40,
				"carLength": 6.4,
				"minCars": 5,
				"maxCars": 5,
				"carsPerCarSet": 5,
				"carCost": 439759,
				"trainWidth": 2.3,
				"minStationLength": 32.0,
				"maxStationLength": 35,
				"baseTrackCost": 55000,
				"baseStationCost": 82500000,
				"trainOperationalCostPerHour": 200,
				"carOperationalCostPerHour": 20,
				"scissorsCrossoverCost": 16500000,
			},
			"elevationMultipliers": {
				"DEEP_BORE": 5.06,
				"STANDARD_TUNNEL": 2.25,
				"CUT_AND_COVER": 1.13,
				"AT_GRADE": 0.30,
				"ELEVATED": 0.70
			},
			"compatibleTrackTypes": ["TMK 2200", "600V Metre LRV (CAT|MS)"],
			"appearance": { "color": "#1264AB"},
			"isFixed": false,
			"location": {
				"city": ["ZAG"],
				"country": ["HR"],
				"continent": ["Southern Europe"],
			},
			"manufacturer": [""],
			"tag": ["Standard LRT"],
		}
	};


	function saveDataForAddTrains() {
		try {
			const storageKey = 'datapacktrains_data';
			const dataPackData = {
				trains: TRAIN_DATA,
				metadata: {
					name: "danTrains",
					version: "0.0.1",
					trainCount: Object.keys(TRAIN_DATA).length,
					lastUpdated: new Date().toISOString()
				}
			};

			localStorage.setItem(storageKey, JSON.stringify(dataPackData));
			console.log(`[TrainDataPack] Saved ${Object.keys(TRAIN_DATA).length} trains`);

		} catch (error) {
			console.error('[TrainDataPack] Failed to save data:', error);
		}
	}

	saveDataForAddTrains();
	console.log('[TrainDataPack] Data pack loaded successfully');
})();